### ISSUE TITLE
When following the github actions workflow integration it causes an error

### ISSUE THREAD

**Issue by 5byuri** [l3montree-dev/devguard#532]
![Image](https://github.com/user-attachments/assets/03786c5d-d2e6-4728-addf-82eb3e34b6b4)

This step needs to be documentated, to fix this, you have to go into the settings of your repo

![Image](https://github.com/user-attachments/assets/e934c756-056a-49fa-a62c-704c778fa11e)

and enable these settings, there is some debate on the settings, since it takes much more responsiblity
![Image](https://github.com/user-attachments/assets/e6ab948d-97d7-43c6-b5e9-04525732384e)

additionally if the github seems to have issues

![Image](https://github.com/user-attachments/assets/918f1b62-dbf0-48c5-998b-3db14a99b0d6)

Apparently the solution is to run another Workflow such as 

```
# .github/workflows/hello-world.yml
name: Hello World

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      # (optional) Code aus dem Repo auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # Hello‑World echo
      - name: Echo Hello World
        run: echo "Hello World"
```

thats makes helps the whole workflow start up (don't ask why it works, it just works, blame github)
