### ISSUE TITLE
Create Upload SARIF CI/CD Integration (reusable workflow + component)

### ISSUE THREAD

**Issue by timbastin** [l3montree-dev/devguard#622]
Currently we provide a different set of github actions. There is actually another command available on the devguard scanner: `devguard-scanner sarif <FILEPATH>`. Would be great to have a dedicated github action for this.

This is how I would like to call it (as a action):

```yaml
jobs:
    code-risk-identification:
        steps:
            - uses: l3montree-dev/devguard-action/.github/workflows/upload-sarif.yml@main
              with:
                  # Path to SARIF file relative to the root of the repository
                  sarif-file: ./results.sarif
                  asset-name: "l3montree/projects/devguard/assets/devguard-api"
                  api-url: https://api.main.devguard.org
              secrets:
                  devguard-token: "${{ secrets.DEVGUARD_TOKEN }}" # you need to create
```

- [ ] Added upload-sarif.yml devguard resuable workflow
- [ ] Added upload-sarif.yml devguard ci cd gitlab component
